isomerpages/moe-jurongwestsec

_about-us/2023 School Calendar for Students.md

undated school calendar link for students

updated school calender link

---

pages/Announcements.md

announcement on SGC collection

announcement on SGC collection

---

_about-us/Direct School Admission (DSA–Sec).md
highlights/2023/_posts/2023-05-03-post-Direct School Admission Exercise.md

updated DSA Information

---

_distinctive/Special Educational Needs.md
_distinctive/collection.yml

updated SEN page

---

_about-us/Financial Assistance Scheme.md
index.md

updated FAS page

---

_data/footer.yml
pages/contact-us.md

updated contact info

---

index.md

edited link for n level page

---

_about-us/School Yearbooks.md

edited school yearbook page

---

_distinctive/Character and Citizenship/Sexuality Education.md

Replaced with information for 2024

Sexuality Education Updates

---

_about-us/Direct School Admission (DSA–Sec).md

Further Updates to the DSA Website

---

_about-us/Direct School Admission (DSA–Sec).md

Minor changes made

---

_cca/Sports & Games.md

frisbee edits

---

_about-us/School Information.md

updated school information

---

_about-us/JWSS Student Council/JWSS CCA Leaders.md
_about-us/JWSS Student Council/JWSS Class Committee.md

Further updates have been made to the CCA Leaders and Class Committee webpages.

CCA Leaders and Class Committee Webpages Updates

---

pages/Secondary One Registration.md

sec 1 registration edtis

---

pages/Secondary One Registration.md

edited sec 1 reg page

---

_cca/Clubs & Societies.md

changed esc to ssc

---

_academic/English Language and Literature.md
_parents-and-students/Parent Support Group.md
pages/GCE O Level 2024 Results Release.md

Major updates to the EL and Lit department website

EL Department Updates

---

_about-us/Executive and Administrative Staff.md
_about-us/School Management Committee.md
_academic/Craft and Technology.md
_academic/English Language and Literature.md
_academic/Humanities.md
_academic/Information and Communications Technology.md
_academic/Mathematics.md
_academic/Mother Tongue Languages.md
_academic/Physical Education.md
_academic/Science.md

removed staff photos

---

_academic/Aesthetics, Craft and Technology.md
_academic/English Language and Literature.md
_academic/Humanities.md
_academic/Mother Tongue Languages.md
_academic/Physical Education.md
_academic/Science.md

edited dept webpage

---

_distinctive/Full Subject–Based Banding (FSBB).md

edited FSBB

---

_about-us/School Management Committee.md

removed smc photo

---

_about-us/School Management Committee.md

edited smc list

---

_about-us/Executive and Administrative Staff.md

removed hirwan frm EAS

---

_about-us/Direct School Admission (DSA–Sec).md

updated DSA details

---

_parents-and-students/Class Form Teachers 2024.md
_parents-and-students/Class Form Teachers 2025.md
_parents-and-students/collection.yml

edit title for FT list 2025

---

index.md

edited DSA application
